export {
  Tensor,
  Session,
  program,
  gradient,
  losses,
  metrics,
  optimize,
} from "affon:_internal/compute/program"

export type {
  Device,
  TensorSpec,
  ProgramDType,
  ProgramShape,
  TensorData,
  TensorInitializerValue,
  TensorValueOptions,
  ProgramArguments,
  SliceRange,
  ProgramFormal,
  ProgramInspection,
  FormalTensor,
  ProgramBuilder,
  Executable,
  ExecutionState,
  Program,
  ProgramNN,
  Initializer,
  LossProgramTemplate,
} from "affon:_internal/compute/program"
