export {
  Tensor,
  Session,
  program,
  gradient,
  metrics,
  optimize,
  update_parameters,
} from "affon:_internal/compute/program"

export type {
  Device,
  OptimizationLevel,
  NumericalPolicy,
  OptimizationGoal,
  ExplanationLevel,
  ResidualPolicy,
  CompileOptions,
  TelemetryOptions,
  SessionOptions,
  CompilationExplanation,
  TensorSpec,
  ProgramDType,
  ProgramShape,
  TensorData,
  TensorInitializerValue,
  TensorValueOptions,
  ProgramArguments,
  SliceRange,
  ProgramFormal,
  ProgramPath,
  ProgramPathSegment,
  ProgramNodeKind,
  ProgramInspectionKind,
  ProgramNode,
  ProgramComponentInspection,
  ProgramInspection,
  FormalTensor,
  ProgramBuilder,
  Executable,
  ExecutionState,
  Program,
  Callable,
  Initializer,
} from "affon:_internal/compute/program"
