import { create_gpt2, type GPT2Weights } from '../../../models/src/gpt2/index.ts'
// HF GPT-2 config/checkpoint adaptation; execution is owned by @affon/models.
import fs from 'std:fs'
import { open_checkpoint } from './checkpoint.ts'
import type { Device, Tensor } from 'affon:compute'
import { validate_causal_buffer } from './gpt2-buffers.ts'
type Config = {
  model_type: string; n_embd: number; n_head: number; n_layer: number;
  n_positions: number; vocab_size: number; n_inner?: number | null;
  activation_function: string; layer_norm_epsilon: number; eos_token_id?: number;
  scale_attn_weights?: boolean; scale_attn_by_inverse_layer_idx?: boolean;
  reorder_and_upcast_attn?: boolean; add_cross_attention?: boolean;
  tie_word_embeddings?: boolean;
}

/** Load tied-head f32 GPT-2 for single-sequence forward and request-local cached greedy generation.
 * @param directory Prepared local HF artifact directory.
 * @param device Execution device; defaults to CPU.
 * @returns Model config, forward(ids), create_session(), and generate(ids, max_new_tokens, options?).
 * @remarks Generation caches K/V by default; use { use_cache: false } for full-prefix execution.
 * Sessions accept only new token IDs per step and own their cache until reset or release.
 */
export function load_gpt2(directory: string, device: Device = 'cpu') {
  const config = JSON.parse(fs.readFileSync(`${directory}/config.json`)) as Config
  if (config.model_type !== 'gpt2' || config.activation_function !== 'gelu_new'
      || config.add_cross_attention || config.scale_attn_by_inverse_layer_idx
      || config.reorder_and_upcast_attn || config.tie_word_embeddings === false) {
    throw new Error('HF adapter supports only tied-head GPT-2 with gelu_new and standard self-attention')
  }
  for (const value of [config.n_embd, config.n_head, config.n_layer, config.n_positions, config.vocab_size, config.n_inner ?? 4 * config.n_embd]) {
    if (!Number.isInteger(value) || value <= 0) throw new Error('Invalid GPT-2 dimensions')
  }
  if (config.n_embd % config.n_head !== 0 || !Number.isFinite(config.layer_norm_epsilon) || config.layer_norm_epsilon <= 0) {
    throw new Error('Invalid GPT-2 head size or normalization epsilon')
  }
  const source = open_checkpoint(directory)
  const weights: Record<string, Tensor> = Object.create(null)
  const expected = new Set<string>()
  const d = config.n_embd
  const inner = config.n_inner ?? 4 * d
  function requireWeight(name: string, shape: number[]) {
    expected.add(name)
    const info = source.catalog[name]
    if (!info || !['F32', 'BF16'].includes(info.dtype) || JSON.stringify(info.shape) !== JSON.stringify(shape)) {
      throw new Error(`Expected f32 ${name} with shape ${JSON.stringify(shape)}`)
    }
    const value = source.read(name)
    weights[name] = value.device === device ? value : value.to(device)
  }
  requireWeight('transformer.wte.weight', [config.vocab_size, d])
  requireWeight('transformer.wpe.weight', [config.n_positions, d])
  requireWeight('transformer.ln_f.weight', [d])
  requireWeight('transformer.ln_f.bias', [d])
  for (let i = 0; i < config.n_layer; i++) {
    const p = `transformer.h.${i}`
    const legacy = `${p}.attn.bias`
    if (source.catalog[legacy]) {
      validate_causal_buffer(source.read(legacy), config.n_positions)
      expected.add(legacy)
      // This deterministic buffer is regenerated by causal_mask during forward.
      delete weights[legacy]
    }
    for (const norm of ['ln_1', 'ln_2']) {
      requireWeight(`${p}.${norm}.weight`, [d])
      requireWeight(`${p}.${norm}.bias`, [d])
    }
    for (const [name, input, output] of [
      ['attn.c_attn', d, 3 * d], ['attn.c_proj', d, d],
      ['mlp.c_fc', d, inner], ['mlp.c_proj', inner, d],
    ] as const) {
      requireWeight(`${p}.${name}.weight`, [input, output])
      requireWeight(`${p}.${name}.bias`, [output])
    }
  }
  // save_pretrained removes the aliased lm_head; fail rather than silently ignore extras.
  for (const name of Object.keys(source.catalog)) {
    if (!expected.has(name)) throw new Error(`Unexpected checkpoint tensor: ${name}`)
  }
  const affine = (prefix: string) => ({ weight: weights[`${prefix}.weight`], bias: weights[`${prefix}.bias`] })
  const parameters: GPT2Weights = {
    tokenEmbedding: weights['transformer.wte.weight'], positionEmbedding: weights['transformer.wpe.weight'], finalNorm: affine('transformer.ln_f'),
    blocks: Array.from({ length: config.n_layer }, (_, i) => {
      const p = `transformer.h.${i}`
      return { attentionNorm: affine(`${p}.ln_1`), feedForwardNorm: affine(`${p}.ln_2`), qkv: affine(`${p}.attn.c_attn`), attentionOutput: affine(`${p}.attn.c_proj`), expand: affine(`${p}.mlp.c_fc`), contract: affine(`${p}.mlp.c_proj`) }
    }),
  }
  const model = create_gpt2({ width: config.n_embd, heads: config.n_head, layers: config.n_layer, contextLength: config.n_positions, vocabSize: config.vocab_size, epsilon: config.layer_norm_epsilon, get eosTokenId() { return config.eos_token_id }, scaleAttention: config.scale_attn_weights }, parameters, device)
  return { ...model, config }
}
