pub const Intention = enum {
    unspecified,
    compute_storage_metadata,
    compute_shape_buffer,
    compute_view_metadata,
    compute_index_buffer,
    compute_batch_index,
    compute_coord_buffer,
    compute_fill_buffer,
    compute_topk_shape,
    compute_topk_index,
    compute_topk_pairs,
    autograd_node,
    autograd_traversal,
    autograd_saved_inputs,
    autograd_saved_meta,
    host_view_copy,
};
