// Experimental native HF GPT-2 implementation; cached and uncached f32 inference.
import fs from 'std:fs'
import checkpoint from 'affon:checkpoint'
import {
  add, cat, contiguous, layer_norm, div, gelu, index_select, masked_fill, matmul,
  mul, no_grad, permute, reshape, softmax, tensor, transpose,
} from 'affon:compute'
import type { Device, Tensor } from 'affon:compute'
import { causal_mask } from '../../transformers/src/sequence.ts'
import { validate_causal_buffer } from './gpt2-buffers.ts'

type Config = {
  model_type: string; n_embd: number; n_head: number; n_layer: number;
  n_positions: number; vocab_size: number; n_inner?: number | null;
  activation_function: string; layer_norm_epsilon: number; eos_token_id?: number;
  scale_attn_weights?: boolean; scale_attn_by_inverse_layer_idx?: boolean;
  reorder_and_upcast_attn?: boolean; add_cross_attention?: boolean;
  tie_word_embeddings?: boolean;
}

/** Load tied-head f32 GPT-2 for single-sequence forward and request-local cached greedy generation.
 * @param directory Prepared local HF artifact directory.
 * @param device Execution device; defaults to CPU.
 * @returns Model config, forward(ids), create_session(), and generate(ids, max_new_tokens, options?).
 * @remarks Generation caches K/V by default; use { use_cache: false } for full-prefix execution.
 * Sessions accept only new token IDs per step and own their cache until reset or release.
 */
export function load_gpt2(directory: string, device: Device = 'cpu') {
  const config = JSON.parse(fs.readFileSync(`${directory}/config.json`)) as Config
  if (config.model_type !== 'gpt2' || config.activation_function !== 'gelu_new'
      || config.add_cross_attention || config.scale_attn_by_inverse_layer_idx
      || config.reorder_and_upcast_attn || config.tie_word_embeddings === false) {
    throw new Error('HF adapter supports only tied-head GPT-2 with gelu_new and standard self-attention')
  }
  for (const value of [config.n_embd, config.n_head, config.n_layer, config.n_positions, config.vocab_size, config.n_inner ?? 4 * config.n_embd]) {
    if (!Number.isInteger(value) || value <= 0) throw new Error('Invalid GPT-2 dimensions')
  }
  if (config.n_embd % config.n_head !== 0 || !Number.isFinite(config.layer_norm_epsilon) || config.layer_norm_epsilon <= 0) {
    throw new Error('Invalid GPT-2 head size or normalization epsilon')
  }
  const weights = checkpoint.load(`${directory}/model.safetensors`) as Record<string, Tensor>
  const expected = new Set<string>()
  const d = config.n_embd
  const inner = config.n_inner ?? 4 * d
  function requireWeight(name: string, shape: number[]) {
    expected.add(name)
    const value = weights[name]
    if (!value || value.dtype !== 'f32' || JSON.stringify(value.shape) !== JSON.stringify(shape)) {
      throw new Error(`Expected f32 ${name} with shape ${JSON.stringify(shape)}`)
    }
    weights[name] = value.device === device ? value : value.to(device)
  }
  requireWeight('transformer.wte.weight', [config.vocab_size, d])
  requireWeight('transformer.wpe.weight', [config.n_positions, d])
  requireWeight('transformer.ln_f.weight', [d])
  requireWeight('transformer.ln_f.bias', [d])
  for (let i = 0; i < config.n_layer; i++) {
    const p = `transformer.h.${i}`
    const legacy = `${p}.attn.bias`
    if (weights[legacy]) {
      validate_causal_buffer(weights[legacy], config.n_positions)
      // This deterministic buffer is regenerated by causal_mask during forward.
      delete weights[legacy]
    }
    for (const norm of ['ln_1', 'ln_2']) {
      requireWeight(`${p}.${norm}.weight`, [d])
      requireWeight(`${p}.${norm}.bias`, [d])
    }
    for (const [name, input, output] of [
      ['attn.c_attn', d, 3 * d], ['attn.c_proj', d, d],
      ['mlp.c_fc', d, inner], ['mlp.c_proj', inner, d],
    ] as const) {
      requireWeight(`${p}.${name}.weight`, [input, output])
      requireWeight(`${p}.${name}.bias`, [output])
    }
  }
  // save_pretrained removes the aliased lm_head; fail rather than silently ignore extras.
  for (const name of Object.keys(weights)) {
    if (!expected.has(name)) throw new Error(`Unexpected checkpoint tensor: ${name}`)
  }
  const scalar = (value: number) => tensor(value, { dtype: 'f32', device })
  const norm = (x: Tensor, prefix: string) => add(mul(
    layer_norm(x, 2, config.layer_norm_epsilon), weights[`${prefix}.weight`]), weights[`${prefix}.bias`])
  const linear = (x: Tensor, prefix: string) => add(matmul(x, weights[`${prefix}.weight`]), weights[`${prefix}.bias`])

  function validateIds(ids: readonly number[]) {
    if (ids.length === 0 || ids.length > config.n_positions || ids.some(id => !Number.isInteger(id) || id < 0 || id >= config.vocab_size)) {
      throw new Error('Expected nonempty valid token IDs within the GPT-2 context limit')
    }
  }

  type Cache = { length: number; layers: { key: Tensor; value: Tensor }[] }
  function run(ids: readonly number[], past?: Cache, cache_enabled = false) {
    validateIds(ids)
    const offset = past?.length ?? 0
    if (offset + ids.length > config.n_positions) throw Error('GPT-2 cache exceeds context limit')
    return no_grad(() => {
      const length = ids.length
      const tokenIds = tensor(Array.from(ids), { dtype: 'f32', device })
      const positions = tensor(Array.from({ length }, (_, i) => offset + i), { dtype: 'f32', device })
      let x = reshape(add(index_select(weights['transformer.wte.weight'], 0, tokenIds),
        index_select(weights['transformer.wpe.weight'], 0, positions)), [1, length, d])
      const hidden_states: Tensor[] = []
      const head = d / config.n_head
      const mask = offset === 0 ? causal_mask(length, { device }) : length === 1 ? null
        : tensor(Array.from({ length }, (_, row) => Array.from({ length: offset + length }, (_, col) => col > offset + row ? 1 : 0)), { dtype: 'f32', device })
      const cache: Cache = { length: offset + length, layers: [] }
      for (let i = 0; i < config.n_layer; i++) {
        hidden_states.push(x)
        const p = `transformer.h.${i}`
        const qkv = linear(norm(x, `${p}.ln_1`), `${p}.attn.c_attn`)
        const split = (offset: number) => contiguous(qkv.slice([':', ':', `${offset}:${offset + d}`]))
        const split_heads = (value: Tensor, tokens: number) => permute(reshape(value,
          [1, tokens, config.n_head, head]), [0, 2, 1, 3])
        // Store sequence-major K/V so append is one contiguous copy per input,
        // rather than a separate Metal buffer copy for every attention head.
        const key = past ? cat([past.layers[i].key, split(d)], 1) : split(d)
        const value = past ? cat([past.layers[i].value, split(2 * d)], 1) : split(2 * d)
        if (cache_enabled) cache.layers.push({ key, value })
        const q = split_heads(split(0), length)
        const k = split_heads(key, offset + length), v = split_heads(value, offset + length)
        let scores = matmul(q, permute(k, [0, 1, 3, 2]))
        if (config.scale_attn_weights !== false) scores = div(scores, scalar(Math.sqrt(head)))
        const attention = matmul(softmax(mask ? masked_fill(scores, mask, -3.4028234663852886e38) : scores, 3), v)
        const merged = reshape(contiguous(permute(attention, [0, 2, 1, 3])), [1, length, d])
        x = add(x, linear(merged, `${p}.attn.c_proj`))
        x = add(x, linear(gelu(linear(norm(x, `${p}.ln_2`), `${p}.mlp.c_fc`)), `${p}.mlp.c_proj`))
      }
      x = norm(x, 'transformer.ln_f')
      hidden_states.push(x)
      return { logits: matmul(x, transpose(weights['transformer.wte.weight'], 0, 1)), hidden_states, cache }
    })
  }

  function forward(ids: readonly number[]): { logits: Tensor; hidden_states: Tensor[] } {
    const { logits, hidden_states } = run(ids)
    return { logits, hidden_states }
  }

  function create_session() {
    let cache: Cache | undefined
    return {
      get length() { return cache?.length ?? 0 },
      reset() { cache = undefined },
      forward(ids: readonly number[]) {
        const result = run(ids, cache, true)
        // Commit only after a successful forward; invalid inputs preserve the session.
        cache = result.cache
        return { logits: result.logits, hidden_states: result.hidden_states }
      },
    }
  }

  function generate(ids: readonly number[], max_new_tokens: number, options: { use_cache?: boolean } = {}): number[] {
    validateIds(ids)
    if (!Number.isInteger(max_new_tokens) || max_new_tokens < 0 || ids.length + max_new_tokens > config.n_positions) {
      throw new Error('Generation budget must be nonnegative and fit within the context limit')
    }
    const output = Array.from(ids)
    const session = options.use_cache === false ? null : create_session()
    try {
    for (let i = 0; i < max_new_tokens; i++) {
      const input = session && i > 0 ? [output[output.length - 1]] : output
      const result = session ? session.forward(input).logits : forward(input).logits
      const row = (result.slice([0, input.length - 1, ':']).to_array() as number[]).flat(Infinity) as number[]
      let best = 0
      for (let j = 1; j < row.length; j++) if (row[j] > row[best]) best = j
      output.push(best)
      if (best === config.eos_token_id) break
    }
    return output
    } finally { session?.reset() }
  }
  return { config, forward, create_session, generate }
}
